### ISSUE TITLE
chore: upload the package to PyPI

### ISSUE THREAD

**Issue by haru52** [haru52/flactomp3#6]
### Tasks

- [x] Read
  - [x] [Python モジュールの配布 — Python 3.11.2 ドキュメント](https://docs.python.org/ja/3/distributing/index.html)
  - [x] [Python のプロジェクトをパッケージングする — Python Packaging User Guide](https://packaging.python.org/ja/latest/tutorials/packaging-projects/)
  - [x] [.pypirc ファイル — Python Packaging User Guide](https://packaging.python.org/ja/latest/specifications/pypirc/)
  - [x] [semantic-release/exec: semantic-release plugin to execute custom shell commands](https://github.com/semantic-release/exec)

### Goal

Completion of all the tasks.

**Comment by haru52** [comment]
- https://github.com/ofek/hatch-vcs/discussions/12
